# Build rules for SPUTIL service program

SPUTILM1.MODULE: sputilm1.sqlrpgle
SPUTILM1.MODULE: SQLRPGIMOD_OPTION := *EVENTF *SECLVL
SPUTILM1.MODULE: SQLRPGIMOD_DBGVIEW := *SOURCE
SPUTILM1.MODULE: SQLRPGIMOD_RPGPPOPT := *LVL2
SPUTILM1.MODULE: CRTSQLRPGIFLAGS += REPLACE(*YES)
SPUTILM1.MODULE: CRTSQLRPGIFLAGS := COMMIT($(COMMIT)) OBJTYPE($(OBJTYPE)) OPTION($(OPTION)) OUTPUT(*PRINT) TEXT('$(subst ','' ,$(TEXT))') TGTRLS($(TGTRLS)) DBGENCKEY($(DBGENCKEY)) USRPRF($(USRPRF)) RPGPPOPT($(RPGPPOPT)) COMPILEOPT('OPTIMIZE($(OPTIMIZE)) INCDIR($(doublequotedINCDIR))') REPLACE(*YES)
SPUTILM2.MODULE: sputilm2.rpgle
SPUTILM2.MODULE: RPGMOD_OPTION := *EVENTF *SECLVL
SPUTILM2.MODULE: RPGMOD_DBGVIEW := *ALL
SPUTILM2.MODULE: CRTRPGMODFLAGS := AUT($(AUT)) DBGVIEW($(DBGVIEW)) DBGENCKEY($(DBGENCKEY)) OPTIMIZE($(OPTIMIZE)) OPTION($(OPTION)) OUTPUT(*PRINT) TEXT('$(subst ','' ,$(TEXT))') TGTRLS($(TGTRLS)) INCDIR($(INCDIR)) DEFINE($(DEFINE)) REPLACE(*YES)

# Service program from binder + modules
SPUTIL.SRVPGM: sputil.bnd SPUTILM1.MODULE SPUTILM2.MODULE
SPUTIL.SRVPGM: SRVPGM_ACTGRP := QILE1
SPUTIL.SRVPGM: CRTSRVPGMFLAGS += REPLACE(*YES)
